= TCRMAN - _(test && commit) || revert_ variant manager 
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Purpose
To provide a quick way to change or apply appropriate *tcr* - 
_(test && commit) || revert_ - variants to projects.


== Motivation
Using tcr can be likened to doing *TDD* on steriods. Inspired 
by projects like _SDKMAN_, the blog post _TCR Variants (test && commit || revert)_ and 
the fact that many developers work as consultants or on diverse projects with
different toolchains, a simple tool for installing and switching variants seemed necessary.

It is hoped that this tool will:

. increase adoption of tcr (and have more code driven by tests).
. be flexible to meet needs of diverse development environments
. expand upon variations 
. share knowledge within the community.

== Getting Started
=== Linux Installation
==== Initial Setup
. Install inotify-tools, if not already installed. 
+
`sudo apt install inotify-tools`
. Clone this project
. Create TCRMAN_HOME environment variable
. Make tcrman script executable:
+
`chmod u+x $TCRMAN_HOME/tcrman`
. Add $TCRMAN_HOME to your path
==== Project Setup
. From your project root, run:
+
`tcrman`
+

A file and directory will be added to the root of your project: _tcr_ 
and _tcrman_ respectively.

=== Mac Installation
_not yet implemented_

=== Windows Installation
_not yet implemented_

== Configuring tcrman
=== The default configuration
Upon initial default installation, tcr for your project will be configured as follows:
. build automation: *gradle*
. test using: *gradle*
. version control: *git*
. tcr variant: *tcra* - the test-commit-revert-all version - the original variant.
. watcher: no

Of course, if you use any of the flags on initial install, explained below, your setup 
will be different.  For example, run command:

`tcrman -b gradle -t gradle -v git -x btcrs -w y`

Will yield configuration: 
. build automation: *gradle*
. test using: *gradle*
. version control: *git*
. tcr variant: *btcrs*
. watcher: y

Re-running `tcrman` at anytime using the flags will use those settings for that and
subsequent uses of tcrman.

=== Configuring build, test and commit/revert toolchains
Once set, most projects will typically use the same build, test and version control
toolchains throughout its lifecycle. As you can probably guess from the explanation 
above, the following option flags are used to configure the toolchains. The flags 
for setting these three are:

. *-b* - the build option.
. *-t* - the test option.
. *-v* - the version control option.

=== Configuring tcr variant
The flag for setting the tcr variant to be executed is *-x*.

=== Configuring watcher
A watcher is used to trigger the configured tcr upon changes in
your projects `src` directory. The flag is *-w* and takes for an 
arg either a *y* to activate a watcher and *n* to disable the 
watcher. The default is disabled.

`tcrman -b gradle -t gradle -v git -x btcrs`

=== Showing the current configuration and available options
Your current configuration is shown at the start of tcrman. If
you wish to also know what options are available, use the *-s*
to show the current config and available options. Note that
no other flags will be processed if this flag is used.

=== Getting help
As you would expect, *-h* displays tcrman help.

=== The (test && commit) || revert Variants
Note that these can all be customized. See below.

The table below explains the variants. Each variant, except the TDD variants, are essentially
abbreviations for the actions taken. The highlighted characters in
the heading are represented in the variant that implements them,
except for the _tdd_ variant which is simply an implementation of
test only. 

.TCR Variants
|===
| Variant | **B**uilds? | **T**ests? | **C**ommits? | **R**everts **S**ource? | **R**everts **A**ll?
| btcra   |    Y      |    Y     |    Y       |        N            |       Y         
| btcrs   |    Y      |    Y     |    Y       |        Y            |       N         
| btdd    |    Y      |    Y     |    N       |        N            |       N         
| tcra    |    N      |    Y     |    Y       |        Y            |       Y          
| tdd     |    N      |    Y     |    N       |        N            |       N          
|===


=== Running (test && commit) || revert
The tcr variants are all simply invoked by running `tcr` from your project root.


=== Customizing
There is a large variety of environments and an even larger variety of tools to
support those environments. A core tenant of this project is that it must be
easily extensible. While the initial releases have been developed to meet the
developers immediate concerns, it is hoped that as others adopt usage of 
*_tcrman_* and begin create customizations, they will share back said customizations
with the community. The patterns used thus far could change to make it more
flexible, but developers who do create their own customizations would do well
to understand and use the patterns used as best they can.



== References
. https://medium.com/@kentbeck_7670/limbo-on-the-cheap-e4cfae840330[Limbo on the Cheap]
. https://medium.com/@tdeniffel/tcr-variants-test-commit-revert-bf6bd84b17d3[TCR Variants (test && commit || revert)]
. https://medium.com/@tdeniffel/tcr-variant-the-storyteller-32c8fdb146f0[TCR Variant: The Storyteller]
. https://medium.com/@tdeniffel/tcr-test-commit-revert-a-test-alternative-to-tdd-6e6b03c22bec[TCR (test && commit || revert). How to use? Alternative to TDD?]
