= TCRMAN - _(test && commit) || revert_ variant manager 
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Purpose
To provide a quick way to change or apply appropriate *tcr* - 
_(test && commit) || revert_ - variants to projects.


== Motivation
Using tcr can be likened to doing *TDD* on steriods. Inspired 
by projects like _SDKMAN_, the blog post _TCR Variants (test && commit || revert)_ and 
the fact that many developers work as consultants or on diverse projects with
different toolchains, a simple tool for installing and switching variants seemed necessary.

It is hoped that this tool will:

. increase adoption of tcr (and have more code driven by tests).
. be flexible to meet needs of diverse development environments
. expand upon variations 
. share knowledge within the community.

== Getting Started
=== Linux Installation
==== Initial Setup
. Install inotify-tools, if not already installed. 
+
`sudo apt install inotify-tools`
. Clone this project
. Create TCRMAN_HOME environment variable
. Make tcrman script executable:
+
`chmod u+x $TCRMAN_HOME/tcrman`
. Add $TCRMAN_HOME to your path
==== Project Setup
. From your project root, run:
+
`tcrman`
+
This will install tcr into your project, which will use:
. build automation: *gradle*
. test using: *gradle*
. version control: *git*
. tcr variant: *tcra* - the test-commit-revert-all version - the original variant.

A file and directory will be added to the root of your project: _tcr_ 
and _tcrman_ respectively.

=== Mac Installation
_not yet implemented_

=== Windows Installation
_not yet implemented_

=== Configuring tcrman
You can configure tcrman to use a different build tool, version 
control system or tcr variant. For example, run command:

`tcrman -b gradle -t gradle -v git -x btcrs`

Most projects will typically use the same build (-b), test (-t) and version control (-v)
toolchains throughout its lifecycle. 

More likely would be to change the executable variant (-x). The table below indicates what
each variant will do. You can also quickly see the available variants by running the show
command (-s):

`tcrman -s`

Any of the options set will remain in effect until changed.

=== The (test && commit) || revert Variants
Note that these can all be customized. See below.

The table below explains the variants. Each variant, except the TDD variants, are essentially
abbreviations for the actions taken.
|===
| Variant | *B*uilds? | *T*ests? | *C*ommits? | *R*everts *S*ource? | *R*everts *A*ll? | *W*atch for save?
| btcra   |    Y      |    Y     |    Y       |        N            |       Y          |     N
| btcraw  |    Y      |    Y     |    Y       |        N            |       Y          |     Y
| btcrs   |    Y      |    Y     |    Y       |        Y            |       N          |     N
| btcrsw  |    Y      |    Y     |    Y       |        Y            |       N          |     Y
| btdd    |    Y      |    Y     |    N       |        N            |       N          |     N
| btddw   |    Y      |    Y     |    N       |        N            |       N          |     Y
| tcra    |    N      |    Y     |    Y       |        Y            |       Y          |     N 
| tcraw   |    N      |    Y     |    Y       |        N            |       Y          |     Y 
| tdd     |    N      |    Y     |    N       |        N            |       N          |     N 
| tddw    |    N      |    Y     |    N       |        N            |       N          |     Y 
|===


=== Running (test && commit) || revert
The tcr variants are all simply invoked by running `tcr` from your project root.


=== Customizing
There is a large variety of environments and an even larger variety of tools to
support those environments. A core tenant of this project is that it must be
easily extensible. While the initial releases have been developed to meet the
developers immediate concerns, it is hoped that as others adopt usage of 
*_tcrman_* and begin create customizations, they will share back said customizations
with the community. The patterns used thus far could change to make it more
flexible, but developers who do create their own customizations would do well
to understand and use the patterns used as best they can.



== References
. https://medium.com/@kentbeck_7670/limbo-on-the-cheap-e4cfae840330[Limbo on the Cheap]
. https://medium.com/@tdeniffel/tcr-variants-test-commit-revert-bf6bd84b17d3[TCR Variants (test && commit || revert)]
. https://medium.com/@tdeniffel/tcr-variant-the-storyteller-32c8fdb146f0[TCR Variant: The Storyteller]
. https://medium.com/@tdeniffel/tcr-test-commit-revert-a-test-alternative-to-tdd-6e6b03c22bec[TCR (test && commit || revert). How to use? Alternative to TDD?]
