#!/usr/bin/env bash
#
# btcra variant - build && ( (test && commit) || revert all)
#
echo -e "executing btcra variant"  &>>./tcrman/tcrman.log
./tcrman/build && ( (./tcrman/test && ./tcrman/commit) || ./tcrman/revert-all)
