#!/usr/bin/env bash
#
# btcra variant - build && ( (test && commit) || revert source)
#
echo -e "executing rtcr variant"  &>>./tcrman/tcrman.log
./tcrman/build && ( (./tcrman/test && ./tcrman/commit) || ./tcrman/revert-source)
