#!/usr/bin/env bash
#
# btcr variant - build && (test && commit || restore)
# for more details - see https://medium.com/@tdeniffel/tcr-variants-test-commit-restore-bf6bd84b17d3
#
echo -e "executing btcr variant"  &>>./tcrman/tcrman.log
./tcrman/build && (./tcrman/test && ./tcrman/commit || ./tcrman/revert-all)
