#!/usr/bin/env bash
#
# relaxed tcr variant - build && (test && commit || restore) variant of tcr
# for more details - see https://medium.com/@tdeniffel/tcr-variants-test-commit-restore-bf6bd84b17d3
#
echo -e "executing rtcr variant"  &>>./tcrman/tcrman.log
./tcrman/build && (./tcrman/test && ./tcrman/commit) || ./tcrman/revert-source
