#!/usr/bin/env bash
#
# the original tcr - test && commit || restore
# for more details - see https://medium.com/@tdeniffel/tcr-variants-test-commit-restore-bf6bd84b17d3
#
echo -e "executing otcr variant"  &>>./tcrman/tcrman.log
(./tcrman/test && ./tcrman/commit) || ./tcrman/revert-all
