#!/usr/bin/env bash
#
# tcra variant - (test && commit) || revert all - the original tcr
#
echo -e "executing tcra variant"  &>>./tcrman/tcrman.log
(./tcrman/test && ./tcrman/commit) || ./tcrman/revert-all
